name: sondv
description: Package includes utilities during working at my company
version: 1.0.0
homepage: https://sondv.dev/
repository: https://github.com/sondv301/sondv

environment:
  sdk: '>=2.18.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
